### ISSUE TITLE
import bili_ticket_gt_python 找不到指定的模块

### ISSUE THREAD

**Issue by YiQunSheng** [Amorter/biliTicker_gt#17]
我的python版本是3.12.4. 翻阅过之前的issue，也有人遇到类似的问题，不过没有找到合适的办法。我的系统是windows 10 企业版1703
import时详细报错是。

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\bili_ticket_gt_python\__init__.py", line 1, in <module>
    from .bili_ticket_gt_python import *
ImportError: DLL load failed while importing bili_ticket_gt_python: 找不到指定的模块。

**Comment by Amorter** [comment]
请安装rust后手动构建并测试，如果构建失败尝试降低ort依赖版本

**Comment by YiQunSheng** [comment]
> 请安装rust后手动构建并测试，如果构建失败尝试降低ort依赖版本

谢谢，我尝试一下！

**Comment by danchaobing** [comment]
弱弱的问一句，ort是哪个，没接触过rust
