### ISSUE TITLE
bili_ticket_gt_python报错

### ISSUE THREAD

**Issue by kevinlikun** [Amorter/biliTicker_gt#4]
环境：python3.10.11
安装bili_ticket_gt_python包

import bili_ticket_gt_python报错

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "\venv\lib\site-packages\bili_ticket_gt_python\__init__.py", line 1, in <module>
    from .bili_ticket_gt_python import *
ImportError: DLL load failed while importing bili_ticket_gt_python: %1 不是有效的 Win32 应用程序。

**Comment by Amorter** [comment]
32位尚未测试，请先使用64位机器，linux和32位的测试会在后续版本更新

**Comment by kevinlikun** [comment]
> 32位尚未测试，请先使用64位机器，linux和32位的测试会在后续版本更新
但是我python是64位的，windows也是64位的

('64bit', 'WindowsPE')
64 位操作系统, 基于 x64 的处理器

**Comment by kevinlikun** [comment]
> 32位尚未测试，请先使用64位机器，linux和32位的测试会在后续版本更新

但是我python是64位的，windows也是64位的

('64bit', 'WindowsPE')
64 位操作系统, 基于 x64 的处理器

**Comment by woshiluo** [comment]
请提供操作系统版本

**Comment by kevinlikun** [comment]
> 请提供操作系统版本

Windows 10 专业版 21H1 19043.928

**Comment by woshiluo** [comment]
有点奇怪，暂时没有思路。

**Comment by woshiluo** [comment]
您可能需要先自行在 https://github.com/Microsoft/onnxruntime/releases/tag/v1.8.1 下来 onnxruntime 的动态链接库并拷贝到运行目录下，我们会考虑在接下来的版本修复这个问题。

**Comment by Amorter** [comment]
> > 请提供操作系统版本
> 
> Windows 10 专业版 21H1 19043.928

v0.2.3应该可以临时解决你的问题，彻底解决请等待后续更新

**Comment by kevinlikun** [comment]
> > > 请提供操作系统版本
> > 
> > 
> > Windows 10 专业版 21H1 19043.928
> 
> v0.2.3应该可以临时解决你的问题，彻底解决请等待后续更新

使用v0.2.5，在原先报错环境下已验证通过，现在可以正常使用，感谢。
